# PyTorch Tutorial 02 - Tensor Basics

In [1]:
import torch

### torch.empty

In [2]:
x = torch.empty(1)  # 1D vector with 1 element
x

tensor([0.])

In [3]:
x = torch.empty(3)  # 1D vector with 3 elements
x

tensor([0., 0., 0.])

In [4]:
x = torch.empty(2, 3)  # 2D matrix
x

tensor([[4.4103e+30, 8.9403e-43, 4.4103e+30],
        [8.9403e-43, 4.4939e+30, 8.9403e-43]])

In [5]:
x = torch.empty(2, 2, 3)  # 3D tensor
x

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [6]:
x = torch.empty(2, 2, 2, 2)  # 4D tensor
x

tensor([[[[9.2755e-39, 1.0561e-38],
          [9.3673e-39, 1.0194e-38]],

         [[1.0561e-38, 4.2246e-39],
          [1.0286e-38, 1.0653e-38]]],


        [[[1.0194e-38, 8.4490e-39],
          [1.0469e-38, 9.3674e-39]],

         [[9.9184e-39, 8.7245e-39],
          [9.2755e-39, 8.9082e-39]]]])

### torch.rand

In [7]:
x = torch.rand(2, 2)
x

tensor([[0.8420, 0.6682],
        [0.4225, 0.5284]])

### torch.zeros

In [8]:
x = torch.zeros(2, 2)
x

tensor([[0., 0.],
        [0., 0.]])

### torch.ones

In [9]:
x = torch.ones(2, 2)
x

tensor([[1., 1.],
        [1., 1.]])

### setting dtype

In [10]:
x.dtype

torch.float32

torch.float32 is set by default

In [11]:
x = torch.ones(2, 2, dtype=torch.double)
x

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [12]:
x.dtype

torch.float64

### x.size()

In [13]:
x.size()

torch.Size([2, 2])

### torch.tensor

In [14]:
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

In [15]:
x = torch.tensor([[2.5, 0.1], [2., 0.]])
x

tensor([[2.5000, 0.1000],
        [2.0000, 0.0000]])

### torch.tensor

In [16]:
x = torch.tensor([1, 2])
x

tensor([1, 2])

In [17]:
x.dtype

torch.int64

### sum of tensors

In [18]:
x = torch.ones(2, 2)
y = torch.ones(2, 2)
print(x)
print(y)
z = x + y
print('\n', z)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])

 tensor([[2., 2.],
        [2., 2.]])


In [19]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([10, 20])
print(x)
print(y)
z = x + y
print('\n', z)

tensor([[1, 2],
        [3, 4]])
tensor([10, 20])

 tensor([[11, 22],
        [13, 24]])


#### the same, but with .add method

In [20]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([10, 20])
x.add(y)

tensor([[11, 22],
        [13, 24]])

### subtraction of tensors

In [21]:
x - y

tensor([[ -9, -18],
        [ -7, -16]])

In [22]:
x.sub(y)

tensor([[ -9, -18],
        [ -7, -16]])

### multiplication of tensors

In [23]:
x * y

tensor([[10, 40],
        [30, 80]])

In [24]:
x.mul(y)

tensor([[10, 40],
        [30, 80]])

### division of tensors

In [25]:
x / y

tensor([[0.1000, 0.1000],
        [0.3000, 0.2000]])

In [26]:
x.div(y)

tensor([[0.1000, 0.1000],
        [0.3000, 0.2000]])

## NB! if we add _ to any arithmetic operator (e.g. 'mul_'), it is the same as 'inplace=True'

### slicing

In [27]:
x = torch.rand(5, 3)
x

tensor([[0.7457, 0.4644, 0.7083],
        [0.9373, 0.7255, 0.9811],
        [0.7784, 0.8741, 0.8435],
        [0.0475, 0.1124, 0.5763],
        [0.8853, 0.3457, 0.9435]])

In [28]:
x[:, 0]  # first column

tensor([0.7457, 0.9373, 0.7784, 0.0475, 0.8853])

In [29]:
x[1, :]  # second row

tensor([0.9373, 0.7255, 0.9811])

### item extraction

In [30]:
x[1, 1]

tensor(0.7255)

In [31]:
x[1, 1].item()

0.7254769802093506

NB! only one item can be extracted

### reshaping with x.view

In [32]:
x = torch.rand(4, 4)
x

tensor([[0.2662, 0.8794, 0.3929, 0.5837],
        [0.3535, 0.8671, 0.2839, 0.1218],
        [0.9937, 0.4911, 0.2519, 0.0792],
        [0.5725, 0.0668, 0.1477, 0.7960]])

In [33]:
x.view(16)

tensor([0.2662, 0.8794, 0.3929, 0.5837, 0.3535, 0.8671, 0.2839, 0.1218, 0.9937,
        0.4911, 0.2519, 0.0792, 0.5725, 0.0668, 0.1477, 0.7960])

In [34]:
x.view(2, 8)

tensor([[0.2662, 0.8794, 0.3929, 0.5837, 0.3535, 0.8671, 0.2839, 0.1218],
        [0.9937, 0.4911, 0.2519, 0.0792, 0.5725, 0.0668, 0.1477, 0.7960]])

In [35]:
x.view(-1, 2)  # -1 means that the size has to be adjusted automatically

tensor([[0.2662, 0.8794],
        [0.3929, 0.5837],
        [0.3535, 0.8671],
        [0.2839, 0.1218],
        [0.9937, 0.4911],
        [0.2519, 0.0792],
        [0.5725, 0.0668],
        [0.1477, 0.7960]])

## conversion from numpy array and vice versa

In [36]:
import numpy as np

In [37]:
a = torch.ones(2, 3, 4)
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### .numpy

In [38]:
b = a.numpy()
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [39]:
a.add_(1)

tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])

In [40]:
b

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]], dtype=float32)

## NB! b was changed too! it happened due to the tensor was created under CPU, not GPU

### torch.from_numpy

In [42]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [43]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [44]:
a += 1
a

array([2., 2., 2., 2., 2.])

In [45]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

## NB! b was changed too! it happened due to the tensor was created under CPU, not GPU

## FOR CUDA VERSION:

In [47]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
#     z.numpy()  # this will not work due to numpy can only handle CPU tensors
    z = z.to("cpu")
    z.numpy()  # this shall work