# PyTorch Tutorial 03 - Gradient Calculation With Autograd

https://www.youtube.com/watch?v=DbeIqrwb_dE&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=4

In [1]:
import torch

In [2]:
x = torch.randn(3)
x

tensor([-0.9552,  0.0792,  1.0910])

In [3]:
x = torch.tensor([1., 2, 3], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [4]:
y = x + 2
y

tensor([3., 4., 5.], grad_fn=<AddBackward0>)

In [5]:
z = y * y * 2
z

tensor([18., 32., 50.], grad_fn=<MulBackward0>)

In [6]:
z = z.mean()
z

tensor(33.3333, grad_fn=<MeanBackward0>)

# computation of gradient with .backward()

In [7]:
z.backward()

In [8]:
x.grad

tensor([4.0000, 5.3333, 6.6667])

# preventing gradient history

### .requires_grad_(False)

In [9]:
x.requires_grad_(False)

tensor([1., 2., 3.])

In [10]:
x

tensor([1., 2., 3.])

#### yet it stores the last computed gradient

In [11]:
x.grad

tensor([4.0000, 5.3333, 6.6667])

#### .backward() now will not compute with a function which employes x as a variable

In [12]:
# z = z.mean()
# z.backward()  # execution of the code will come with an error

### .detach_()

In [13]:
x = torch.tensor([1., 2, 3], requires_grad=True)
y = x + 2
print(x, y)
x.detach_()  # !!!
print(x, y)  # in this case y will come with gradient function 
             # as it was set before autogradient parameter was detached from x variable

tensor([1., 2., 3.], requires_grad=True) tensor([3., 4., 5.], grad_fn=<AddBackward0>)
tensor([1., 2., 3.]) tensor([3., 4., 5.], grad_fn=<AddBackward0>)


### with torch.no_grad()

In [14]:
x = torch.tensor([1., 2, 3], requires_grad=True)
with torch.no_grad():  # in this line we say that automatic computation of gradient must be skipped
    y = x + 2
    print(x, y)

tensor([1., 2., 3.], requires_grad=True) tensor([3., 4., 5.])


# accumulation of gradients

#### one iteration

In [15]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(1):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])


#### three iteration

In [16]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


# zeroing gradients with weights.grad.zero_()

In [17]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()  # !!!
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([0., 0., 0., 0.])
tensor([3., 3., 3., 3.])
tensor([0., 0., 0., 0.])
tensor([3., 3., 3., 3.])
tensor([0., 0., 0., 0.])
